const USERS=[
{u:"shreyas",p:"SHR129",balance:2000000000,limit:8000,withdrawal:8000},
{u:"zain",p:"zai129",balance:9000000000,limit:5000,withdrawal:5000},
{u:"rana",p:"ran129",balance:3650000000,limit:6000,withdrawal:6000},
{u:"gani",p:"gan129",balance:7800000,limit:4000,withdrawal:4000},
{u:"dhanush",p:"dha129",balance:3500000,limit:0,withdrawal:0},
{u:"nadeem",p:"nad129",balance:7500000,limit:2500,withdrawal:2500}];
const STOCKS=[
["RELIANCE","Reliance Industries",2941.25,1.18],["TCS","Tata Consultancy Services",4178.40,-0.42],
["INFY","Infosys",1810.65,.74],["HDFCBANK","HDFC Bank",1972.10,.31],["ICICIBANK","ICICI Bank",1427.80,1.02],
["SBIN","State Bank of India",926.55,-.63],["ITC","ITC Ltd",493.20,.52],["BHARTIARTL","Bharti Airtel",1888.30,1.41],
["LT","Larsen & Toubro",3892,.16],["MARUTI","Maruti Suzuki",12740,-.28]];
let user=null,prices=STOCKS.map(x=>x[2]),watch=new Set(["RELIANCE","INFY"]),cash=0,holdings={},tradeSide="BUY",transactions=[],withdrawals=[];
const money=n=>"₹"+Number(n).toLocaleString("en-IN",{maximumFractionDigits:2});
const $=id=>document.getElementById(id);

function login(){const u=$("username").value.trim().toLowerCase(),p=$("password").value,c=$("clientId").value.trim();user=USERS.find(x=>x.u===u&&x.p===p&&c==="BRCLT-45871293");if(!user){$("loginError").textContent="Invalid login details.";return}cash=user.balance;sessionStorage.setItem("msnUser",u);$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("topUser").textContent="● "+u;$("welcome").textContent=u;renderAll()}
function logout(){sessionStorage.clear();location.reload()}
$("loginBtn").onclick=login;$("password").addEventListener("keydown",e=>{if(e.key==="Enter")login()});$("logoutBtn").onclick=logout;

function renderMarkets(){const q=($("search")?.value||"").toUpperCase();$("marketRows").innerHTML=STOCKS.map((s,i)=>({s,i})).filter(x=>x.s[0].includes(q)||x.s[1].toUpperCase().includes(q)).map(x=>`<tr><td class="symbol">${x.s[0]}</td><td>${x.s[1]}</td><td>${money(prices[x.i])}</td><td class="${x.s[3]>=0?"up":"down"}">${x.s[3]>=0?"+":""}${x.s[3].toFixed(2)}%</td><td><button class="star ${watch.has(x.s[0])?"on":""}" onclick="toggleWatch('${x.s[0]}')">★</button></td><td><button class="trade-btn" onclick="goTrade('${x.s[0]}')">Trade</button></td></tr>`).join("")||"<tr><td colspan='6'>No stocks found.</td></tr>"}
function toggleWatch(s){watch.has(s)?watch.delete(s):watch.add(s);renderAll()}
function renderWatch(){$("watchRows").innerHTML=[...watch].map(sym=>{const i=STOCKS.findIndex(x=>x[0]===sym);return `<div class="mover"><div><b>${sym}</b><div class="muted">${STOCKS[i][1]}</div></div><div>${money(prices[i])}<br><span class="${STOCKS[i][3]>=0?"up":"down"}">${STOCKS[i][3]>=0?"+":""}${STOCKS[i][3].toFixed(2)}%</span></div></div>`}).join("")||"<p class='muted'>Watchlist is empty.</p>"}
function portfolio(){let value=cash,pnl=0;Object.entries(holdings).forEach(([sym,h])=>{let i=STOCKS.findIndex(x=>x[0]===sym),v=h.qty*prices[i];value+=v;pnl+=(prices[i]-h.avg)*h.qty});return{value,pnl}}
function renderPortfolio(){const p=portfolio();$("portValue").textContent=money(p.value);$("portCash").textContent=money(cash);$("portPnl").textContent=money(p.pnl);$("portPnl").className=p.pnl>=0?"up":"down";$("dashPortfolio").textContent=money(p.value);$("dashPnl").textContent=(p.pnl>=0?"+":"")+money(p.pnl)+" simulated P&L";$("balance").textContent=money(user.balance);$("dashLimit").textContent=money(user.limit);$("wdBalance").textContent=money(user.balance);$("wdLimit").textContent=money(user.limit);$("portfolioRows").innerHTML=Object.entries(holdings).map(([sym,h])=>{let i=STOCKS.findIndex(x=>x[0]===sym),v=h.qty*prices[i],pl=(prices[i]-h.avg)*h.qty;return `<tr><td class="symbol">${sym}</td><td>${h.qty}</td><td>${money(h.avg)}</td><td>${money(prices[i])}</td><td>${money(v)}</td><td class="${pl>=0?"up":"down"}">${money(pl)}</td></tr>`}).join("")||"<tr><td colspan='6' class='muted'>No simulated holdings.</td></tr>"}
function renderSnapshot(){$("snapshot").innerHTML=STOCKS.slice(0,5).map((s,i)=>`<div class="snapshot"><span><b>${s[0]}</b><br><small class="muted">${money(prices[i])}</small></span><span class="${s[3]>=0?"up":"down"}">${s[3]>=0?"+":""}${s[3].toFixed(2)}%</span></div>`).join("")}
function drawChart(){const c=$("marketChart");if(!c)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1,w=r.width,h=270;c.width=w*d;c.height=h*d;const x=c.getContext("2d");x.scale(d,d);x.clearRect(0,0,w,h);let pts=Array.from({length:55},(_,i)=>h*.52-Math.sin(i/4)*h*.15-i*.8+(Math.random()-.5)*18);x.strokeStyle="#31df7b";x.lineWidth=2;x.beginPath();pts.forEach((y,i)=>{let xx=8+i*(w-16)/(pts.length-1);i?x.lineTo(xx,y):x.moveTo(xx,y)});x.stroke()}
function goTrade(sym){showPage("trade");$("tradeStock").value=sym;updateEstimate()}
function updateEstimate(){const i=STOCKS.findIndex(x=>x[0]===$("tradeStock").value),q=Math.max(0,Number($("tradeQty").value)||0);$("estimate").textContent=money(prices[i]*q)}
$("search").oninput=renderMarkets;$("tradeQty").oninput=updateEstimate;$("tradeStock").onchange=updateEstimate;$("buyTab").onclick=()=>{tradeSide="BUY";$("buyTab").classList.add("selected");$("sellTab").classList.remove("selected")};$("sellTab").onclick=()=>{tradeSide="SELL";$("sellTab").classList.add("selected");$("buyTab").classList.remove("selected")};
function executeTrade(){const sym=$("tradeStock").value,i=STOCKS.findIndex(x=>x[0]===sym),q=Math.floor(Number($("tradeQty").value)),price=prices[i];if(q<1)return;if(!holdings[sym])holdings[sym]={qty:0,avg:0};let h=holdings[sym];if(tradeSide==="BUY"){let cost=q*price;if(cost>cash){$("tradeMessage").textContent="Insufficient simulated cash.";return}h.avg=(h.avg*h.qty+cost)/(h.qty+q);h.qty+=q;cash-=cost;transactions.push(["Today","Simulated BUY "+sym,"—",money(cost),money(cash)])}else{if(q>h.qty){$("tradeMessage").textContent="Not enough simulated shares.";return}cash+=q*price;h.qty-=q;if(!h.qty)delete holdings[sym];transactions.push(["Today","Simulated SELL "+sym,money(q*price),"—",money(cash)])}$("tradeMessage").textContent="Simulated order completed.";renderAll()}
$("tradeBtn").onclick=executeTrade;
function renderWithdrawals(){$("wdHistory").innerHTML=withdrawals.length?withdrawals.map(w=>`<tr><td>${w.date}</td><td>${money(w.amount)}</td><td class="amber-text">${w.status}</td><td>${w.ref}</td></tr>`).join(""):`<tr><td>12-Aug-2026</td><td>${money(user.withdrawal)}</td><td class="amber-text">PENDING</td><td>MB-DEMO-${user.u.toUpperCase()}</td></tr>`}
$("wdBtn").onclick=()=>{const a=Number($("wdAmount").value);if(user.limit===0){$("wdMsg").textContent="Withdrawals are disabled for this demo account.";return}if(!a||a<1||a>user.limit){$("wdMsg").textContent="Amount exceeds the configured demo withdrawal limit.";return}withdrawals.push({date:new Date().toLocaleDateString("en-IN"),amount:a,status:"PENDING",ref:"MB-DEMO-"+Date.now().toString().slice(-6)});$("wdMsg").textContent="Withdrawal request recorded as PENDING (simulation).";renderWithdrawals()};
function renderStatement(){$("statementClient").textContent=user.u;const rows=[["12-Aug-2026","Opening simulated balance","—","—",money(user.balance),"SIMULATION"],...transactions];$("statementRows").innerHTML=rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td></tr>`).join("")}
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="dashboard")drawChart()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll("[data-goto]").forEach(b=>b.onclick=()=>showPage(b.dataset.goto));
function renderAll(){renderMarkets();renderWatch();renderPortfolio();renderSnapshot();renderWithdrawals();renderStatement();$("tradeStock").innerHTML=STOCKS.map(s=>`<option>${s[0]}</option>`).join("");updateEstimate();drawChart()}
setInterval(()=>{prices=prices.map(p=>p*(1+(Math.random()-.5)*.001));STOCKS.forEach(s=>s[3]=Math.max(-5,Math.min(5,s[3]+(Math.random()-.5)*.08)));if(!document.getElementById("appView").classList.contains("hidden"))renderAll()},5000);
window.addEventListener("resize",drawChart);
const saved=sessionStorage.getItem("msnUser");if(saved){$("username").value=saved;user=USERS.find(x=>x.u===saved);if(user){cash=user.balance;$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("topUser").textContent="● "+user.u;$("welcome").textContent=user.u;renderAll()}}
